[theme]
base = "dark"
primaryColor = "#f093fb"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#302b63"
textColor = "#b8b8d4"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
